<?xml version="1.0"?>
<robot name="Upper_leg" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Import Macros -->
  <xacro:macro name="cylinder_inertia" params="m r h">
	  <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
	    iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
	    izz="${m*r*r/2}"
	  />
	</xacro:macro>

	<xacro:macro name="box_inertia" params="m x y z">
	  <inertia  ixx="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0"
	    iyy="${m*(x*x+z*z)/12}" iyz = "0"
	    izz="${m*(x*x+z*z)/12}"
	  />
	</xacro:macro>

	<xacro:macro name="sphere_inertia" params="m r">
	  <inertia  ixx="${2*m*r*r/5}" ixy = "0" ixz = "0"
	    iyy="${2*m*r*r/5}" iyz = "0"
	    izz="${2*m*r*r/5}"
	  />
	</xacro:macro>

<!-- legs -->
<xacro:property name="upper_leg_height" value="0.10" />
<xacro:property name="upper_leg_radius" value="0.02" />
<xacro:property name="upper_leg_mass" value="2.0" />

<xacro:property name="sphere_r" value="0.02" />
<xacro:property name="sphere_mass" value="0.02" />
  
  <!-- Femur -->
  <link name="upper_leg">
    <inertial>
      <origin xyz="0 0 ${upper_leg_height/2}"/>
      <mass value="${upper_leg_mass}" />
      <xacro:cylinder_inertia  m="${upper_leg_mass}" r="${upper_leg_radius}" h="${upper_leg_height}" />
    </inertial>
    <collision>
      <origin xyz="0 0 ${upper_leg_height/2}" rpy="0 0 0" />
      <geometry>
	      <cylinder length="${upper_leg_height}" radius="${upper_leg_radius}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 ${upper_leg_height/2}" rpy="0 0 0" />
      <geometry>
	      <cylinder length="${upper_leg_height}" radius="${upper_leg_radius}"/>
      </geometry>
    <material name="Gray" />
   </visual>
</link>
</robot>
